GET http://localhost:5065/games

###
GET http://localhost:5065/games/04843a23-a7b5-48c8-92cb-9d0af88238b3

###
POST http://localhost:5065/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId": "d4e5f678-90a1-b2c3-d4e5-f67890a1b2c3",
    "price": 19.99,
    "releaseDate": "2011-11-18",
    "description": "A sandbox game that allows players to build and explore virtual worlds made of blocks."
}

###
PUT http://localhost:5065/games/4c7bc428-be57-4855-8a51-63ab6f035e14
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": "d4e5f678-90a1-b2c3-d4e5-f67890a1b2c3",
    "price": 9.99,
    "releaseDate": "1992-07-15",
    "description": "The most iconic fighting game of all time!"
}

###
DELETE http://localhost:5065/games/4c7bc428-be57-4855-8a51-63ab6f035e14

###
GET http://localhost:5065/genres